### ISSUE TITLE
go panic on upload

### ISSUE THREAD

**Issue by kenperkins** [jrperritt/rack#225]
```
/data/src/rack [flavor-extra-specs]* $ rack files object upload --container kptest2 --file ~/Pictures/IMG_1179.JPG --name test
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x38 pc=0x1f4e62]

goroutine 6 [running]:
github.com/jrperritt/rack/internal/github.com/rackspace/gophercloud/openstack/objectstorage/v1/objects.Create(0xc2080a8780, 0xc2080833b1, 0x7, 0xc2080833b8, 0x4, 0xa127a0, 0xc20802e068, 0xa127d0, 0xc208077500, 0x0, ...)
	/Users/ken/go/src/github.com/jrperritt/rack/internal/github.com/rackspace/gophercloud/openstack/objectstorage/v1/objects/requests.go:237 +0x9b2
github.com/jrperritt/rack/internal/github.com/rackspace/gophercloud/rackspace/objectstorage/v1/objects.Create(0xc2080a8780, 0xc2080833b1, 0x7, 0xc2080833b8, 0x4, 0xa127a0, 0xc20802e068, 0xa127d0, 0xc208077500, 0x0, ...)
	/Users/ken/go/src/github.com/jrperritt/rack/internal/github.com/rackspace/gophercloud/rackspace/objectstorage/v1/objects/delegate.go:37 +0xaa
github.com/jrperritt/rack/commands/filescommands/objectcommands.(*commandUpload).Execute(0xc20802e020, 0xc208030820)
	/Users/ken/go/src/github.com/jrperritt/rack/commands/filescommands/objectcommands/upload.go:162 +0x17f
github.com/jrperritt/rack/handler.func·003()
	/Users/ken/go/src/github.com/jrperritt/rack/handler/handle.go:175 +0xf0
created by github.com/jrperritt/rack/handler.handleExecute
	/Users/ken/go/src/github.com/jrperritt/rack/handler/handle.go:178 +0xc0e

goroutine 1 [chan receive]:
github.com/jrperritt/rack/handler.Handle(0xa12610, 0xc20802e020)
	/Users/ken/go/src/github.com/jrperritt/rack/handler/handle.go:110 +0x4c3
github.com/jrperritt/rack/commands/filescommands/objectcommands.actionUpload(0xc208077420)
	/Users/ken/go/src/github.com/jrperritt/rack/commands/filescommands/objectcommands/upload.go:86 +0xd4
github.com/jrperritt/rack/internal/github.com/codegangsta/cli.Command.Run(0x51d7b0, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc208056ae0, 0x52, 0x552b70, ...)
	/Users/ken/go/src/github.com/jrperritt/rack/internal/github.com/codegangsta/cli/command.go:118 +0x1044
github.com/jrperritt/rack/internal/github.com/codegangsta/cli.(*App).RunAsSubcommand(0xc208072900, 0xc208076ee0, 0x0, 0x0)
	/Users/ken/go/src/github.com/jrperritt/rack/internal/github.com/codegangsta/cli/app.go:257 +0xc2a
github.com/jrperritt/rack/internal/github.com/codegangsta/cli.Command.startApp(0x5174d0, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x591db0, 0x25, 0x0, ...)
	/Users/ken/go/src/github.com/jrperritt/rack/internal/github.com/codegangsta/cli/command.go:183 +0x505
github.com/jrperritt/rack/internal/github.com/codegangsta/cli.Command.Run(0x5174d0, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x591db0, 0x25, 0x0, ...)
	/Users/ken/go/src/github.com/jrperritt/rack/internal/github.com/codegangsta/cli/command.go:45 +0x14ee
github.com/jrperritt/rack/internal/github.com/codegangsta/cli.(*App).RunAsSubcommand(0xc208072300, 0xc2080769a0, 0x0, 0x0)
	/Users/ken/go/src/github.com/jrperritt/rack/internal/github.com/codegangsta/cli/app.go:257 +0xc2a
github.com/jrperritt/rack/internal/github.com/codegangsta/cli.Command.startApp(0x5106f0, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x5922b0, 0x23, 0x0, ...)
	/Users/ken/go/src/github.com/jrperritt/rack/internal/github.com/codegangsta/cli/command.go:183 +0x505
github.com/jrperritt/rack/internal/github.com/codegangsta/cli.Command.Run(0x5106f0, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x5922b0, 0x23, 0x0, ...)
	/Users/ken/go/src/github.com/jrperritt/rack/internal/github.com/codegangsta/cli/command.go:45 +0x14ee
github.com/jrperritt/rack/internal/github.com/codegangsta/cli.(*App).Run(0xc208072200, 0xc20800a000, 0xa, 0xa, 0x0, 0x0)
	/Users/ken/go/src/github.com/jrperritt/rack/internal/github.com/codegangsta/cli/app.go:160 +0xd0c
main.main()
	/data/src/rack/main.go:33 +0x38f

goroutine 11 [select]:
net/http.(*persistConn).readLoop(0xc208074160)
	/usr/local/go/src/net/http/transport.go:928 +0x9ce
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 12 [IO wait]:
net.(*pollDesc).Wait(0xc208010920, 0x77, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitWrite(0xc208010920, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:93 +0x43
net.(*netFD).Write(0xc2080108c0, 0xc208d12000, 0x1035, 0x2000, 0x0, 0xa12000, 0xc208cfbb88)
	/usr/local/go/src/net/fd_unix.go:335 +0x5ee
net.(*conn).Write(0xc20802e078, 0xc208d12000, 0x1035, 0x2000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:129 +0xdc
crypto/tls.(*Conn).writeRecord(0xc2080a4dc0, 0x17, 0xc208095000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:748 +0x4f3
crypto/tls.(*Conn).Write(0xc2080a4dc0, 0xc208095000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:880 +0x411
bufio.(*Writer).flush(0xc208cdb380, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:530 +0xe0
bufio.(*Writer).ReadFrom(0xc208cdb380, 0xa21d18, 0xc208d0e6a0, 0x2dead, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:654 +0x117
io.Copy(0xa21c18, 0xc208cdb380, 0xa21d18, 0xc208d0e6a0, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:358 +0x13d
net/http.(*transferWriter).WriteBody(0xc208d10150, 0xa21c18, 0xc208cdb380, 0x0, 0x0)
	/usr/local/go/src/net/http/transfer.go:214 +0x7c7
net/http.(*Request).write(0xc208034ea0, 0xa21c18, 0xc208cdb380, 0xa21c00, 0xc208cfeb40, 0x0, 0x0)
	/usr/local/go/src/net/http/request.go:448 +0xada
net/http.(*persistConn).writeLoop(0xc208074160)
	/usr/local/go/src/net/http/transport.go:951 +0x28d
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:661 +0xcbc
```

**Comment by jrperritt** [comment]
Fixed here: https://github.com/jrperritt/rack/commit/acc5f189a5994095867cbe63c579efe24d8ca549 (or near there)
