### ISSUE TITLE
Go Panic when generating keypair

### ISSUE THREAD

**Issue by kenperkins** [jrperritt/rack#89]
```
/data/src/rack [cloud-files-ops-and-piping] $ ./rack --region iad servers keypair generate --keypair rack-cli
panic: interface conversion: interface is *keypairs.CreateOpts, not *keypaircommands.paramsGenerate

goroutine 1 [running]:
github.com/jrperritt/rack/serverscommands/keypaircommands.(*commandGenerate).HandleSingle(0xc208038048, 0xc2082536d0, 0x0, 0x0)
	/Users/ken/go/src/github.com/jrperritt/rack/serverscommands/keypaircommands/generate.go:80 +0x12d
github.com/jrperritt/rack/handler.Handle(0x1012198, 0xc208038048)
	/Users/ken/go/src/github.com/jrperritt/rack/handler/handle.go:133 +0x10fe
github.com/jrperritt/rack/serverscommands/keypaircommands.actionGenerate(0xc2080882a0)
	/Users/ken/go/src/github.com/jrperritt/rack/serverscommands/keypaircommands/generate.go:50 +0xd4
github.com/codegangsta/cli.Command.Run(0x434390, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc208042180, 0x5d, 0x4464b0, ...)
	/Users/ken/go/src/github.com/codegangsta/cli/command.go:118 +0x1044
github.com/codegangsta/cli.(*App).RunAsSubcommand(0xc208066500, 0xc2080880e0, 0x0, 0x0)
	/Users/ken/go/src/github.com/codegangsta/cli/app.go:257 +0xc2a
github.com/codegangsta/cli.Command.startApp(0x41d310, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x47bbf0, 0x22, 0x0, ...)
	/Users/ken/go/src/github.com/codegangsta/cli/command.go:183 +0x505
github.com/codegangsta/cli.Command.Run(0x41d310, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x47bbf0, 0x22, 0x0, ...)
	/Users/ken/go/src/github.com/codegangsta/cli/command.go:45 +0x14ee
github.com/codegangsta/cli.(*App).RunAsSubcommand(0xc208066400, 0xc208088000, 0x0, 0x0)
	/Users/ken/go/src/github.com/codegangsta/cli/app.go:257 +0xc2a
github.com/codegangsta/cli.Command.startApp(0x420570, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x464e30, 0x1c, 0x0, ...)
	/Users/ken/go/src/github.com/codegangsta/cli/command.go:183 +0x505
github.com/codegangsta/cli.Command.Run(0x420570, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x464e30, 0x1c, 0x0, ...)
	/Users/ken/go/src/github.com/codegangsta/cli/command.go:45 +0x14ee
github.com/codegangsta/cli.(*App).Run(0xc208066300, 0xc20800a000, 0x8, 0x8, 0x0, 0x0)
	/Users/ken/go/src/github.com/codegangsta/cli/app.go:160 +0xd0c
main.main()
	/data/src/rack/main.go:38 +0x310

goroutine 5 [chan receive]:
github.com/jrperritt/rack/handler.func·001()
	/Users/ken/go/src/github.com/jrperritt/rack/handler/context.go:47 +0x6d
created by github.com/jrperritt/rack/handler.(*Context).ListenAndReceive
	/Users/ken/go/src/github.com/jrperritt/rack/handler/context.go:63 +0xcc

goroutine 10 [runnable]:
net/http.(*persistConn).readLoop(0xc2080760b0)
	/usr/local/go/src/net/http/transport.go:928 +0x9ce
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 11 [select]:
net/http.(*persistConn).writeLoop(0xc2080760b0)
	/usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:661 +0xcbc
```

**Comment by kenperkins** [comment]
I think @jrperritt fixed this in 93350ba5464ee58d623eb83011371942183eae36
